// Generated by spider on 2022-05-30 23:36:07.586769

part of 'resources.dart';

class Images {
  Images._();

  static const String bgimage = 'assets/images/bgimage.png';
  static const String nodata = 'assets/images/nodata.png';
  static const String nosearch = 'assets/images/nosearch.png';
  static const String splash = 'assets/images/splash.png';
}
