// Generated by spider on 2022-05-30 23:36:07.737400

part of 'resources.dart';

class Svgs {
  Svgs._();

  static const String alphabetSelected = 'assets/svgs/alphabet_selected.svg';
  static const String alphabetUnselected =
      'assets/svgs/alphabet_unselected.svg';
  static const String episodes = 'assets/svgs/episodes.svg';
  static const String filter = 'assets/svgs/filter.svg';
  static const String homepage = 'assets/svgs/homepage.svg';
  static const String location = 'assets/svgs/location.svg';
  static const String search = 'assets/svgs/search.svg';
  static const String settings = 'assets/svgs/settings.svg';
  static const String toListView = 'assets/svgs/toListView.svg';
  static const String togridview = 'assets/svgs/togridview.svg';
}
